version: "3"
services:  
  msclient:
    build: .\ms-client
    container_name: "msclient-dockercompose"
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    networks:
      - amigoprogramador

  msdebitcard:
    build: .\ms-debitcard
    container_name: "msdebitcard-dockercompose"
    ports:
      - 8081:8081
    depends_on:
      - mongodb
      - msclient
      - kafka
    networks:
      - amigoprogramador
  
  mstransaction:
    build: .\ms-transaction
    container_name: "mstransaction-dockercompose"
    ports:
      - 8082:8082
    depends_on:
      - mongodb
      - msdebitcard
      - kafka
    networks:
      - amigoprogramador
  
  mongodb:
    image: mongo:latest
    container_name: mongodb-dockercompose
    ports:
      - 27017:27017  
    networks:
      - amigoprogramador
  
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    restart: always
    ports:
      - 2181:2181
    networks:
      - amigoprogramador
      
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    restart: always
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_CREATE_TOPICS=TRANSFERENCE:1:1
      - KAFKA_BROKER_ID=1
    networks:
      - amigoprogramador 
      
      
networks:
  amigoprogramador:
